from collections.abc import Iterable
from pathlib import Path

from carron.core.types import GeneratedArtifact

HEADER = "# This file was generated by Carron. Do not edit manually.\n\n"


def write_artifacts(artifacts: Iterable[GeneratedArtifact], output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for artifact in artifacts:
        path = output_dir / artifact.relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(HEADER + artifact.content)
        paths.append(path)
    return paths
